### ISSUE TITLE
Nuova feature: partenza random del giocatore

### ISSUE THREAD

**Issue by gvnnz** [gvnnz/tris#24]
All'inizio il programma sceglie a random il giocatore che fa la prima mossa.

**Comment by Ace-Miky** [comment]
@gvnnz Ho gia' verificato che funziona

**Comment by gvnnz** [comment]
Grande @Ace-Miky, perfetto. Ho spostato il tuo commit https://github.com/gvnnz/tris/commit/1bff0f79828c30144509f602689fa7fbbeb0568e su un altro branch (chiamato `random-player-start`) così possiamo terminare i lavori di refactoring sull'altro. Finito il refactoring uniamo tutto.

**Comment by Ace-Miky** [comment]
Bene! A domani
