### ISSUE TITLE
Refactoring: classe Player

### ISSUE THREAD

**Issue by gvnnz** [gvnnz/tris#25]
Al momento abbiamo un po' di variabili relative al giocatore sparse in giro per il codice.  @Ace-Miky introduciamo una nuova classe Player con due proprietà: il nome del giocatore il suo simbolo associato. In questo modo raggruppiamo le variabili relative al giocatore in una classe, così da rendere il tutto più chiaro/leggibile.

**Comment by Ace-Miky** [comment]
@gvnnz Questa la puoi fare tu per favore? Che poi vorrei studiarmi quello che hai fatto prima della prossima lezione... Non ho ancora dimestichezza con il comporre le classi: scrivi tu che poi me lo studio bene, grazie!
