### ISSUE TITLE
Evitare che i due player possano scegliere lo stesso nome

### ISSUE THREAD

**Issue by Ace-Miky** [gvnnz/tris#31]
@gvnnz Sembrera' una banalita' ma bisognerebbe fare in modo che se il player1 immette un nome, il player2 non puo' inserire lo stesso nome; quindi in quel caso il programma stamperebbe un messaggio di errore del tipo: "player name alredy exist!"

**Comment by gvnnz** [comment]
No anzi direi che è un'ottima idea, per evitare confusioni.

Ho aggiornato il titolo della issue per renderlo più chiaro.
